services:
  frontend:
    build:
      context: .
      dockerfile: .Dockerfile
      args:
        # Pass build-time environment variables
        # These should be defined in your .env file or set in your CI/CD pipeline
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
        VITE_APP_ENV: ${VITE_APP_ENV:-production}
    container_name: blogapp-frontend
    ports:
      - "8081:80"
    networks:
      - blogapp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    labels:
      - "com.blogapp.description=Blog Application Frontend"
      - "com.blogapp.service=frontend"

networks:
  blogapp_network:
    external: true
